### ISSUE TITLE
use chromakey filter 

### ISSUE THREAD

**Issue by miraculixx** [steven-varga/chromakey#1]
great tool & inspiration

For some reasons I could only get it to work with the chromakey filter, the colorkey filter created a distorted image (using an Elgato green screen). 

Here's the command I ended up with https://gist.github.com/miraculixx/49a3a8cad895f8a72b3a6bdc089d0580

**Comment by steven-varga** [comment]
in the previous versions the I had it reverse, the chromakey failed. In any event, I looked at your script and shamelessly lifted the idea of naming the pseudo camera to 'greenscreen'. Also added live screen grab functionality. I just realised the big **steal** was the `exclusive_caps=1` flag, to make it work with google conference. Thanks!

To sum it up: back to chromakey, and there is screen grab option... see if this checks out. Now I am thinking to write this in C++ with openCV
